pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - check-success=Sider
      - check-success=Semantic Pull Request
      - check-success=Python Unit Tests (MariaDB)
      - check-success=Python Unit Tests (Postgres)
      - check-success=UI Tests (Cypress)
      - check-success=security/snyk (frappe)
      - label!=dont-merge
      - label!=squash
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic squash on CI success and review
    conditions:
      - check-success=Sider
      - check-success=Python Unit Tests (MariaDB)
      - check-success=Python Unit Tests (Postgres)
      - check-success=UI Tests (Cypress)
      - check-success=security/snyk (frappe)
      - label!=dont-merge
      - label=squash
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
